sudo: false
language: node_js
node_js:
- '7'
os:
  - linux
  - osx
  - windows
before_install:
- npm install -g docarys-material
after_success:
- npm run codacy-cover
deploy:
  on:
    tags: true
  provider: npm
  email: sesispla@outlook.com
  api_key:
    secure: okyRq3skY4j+QVJfoWUcjC58DrduhIq06+HrdQhFby5pCKKwB3mOHIZHC3rE0Wrvj/cXjvvoL1fQlvPm/WKHsDxmsSUEkpPe5Dlj1x0ra3IFMB9pCekl7vy+zr+bi0h5yJXC3Lj4iU2SI09WDT5KamNMw7kqxWiGK7V5TunisCkkQFIOM3+bwOf3qZWc/hbsOE1Nspw3jC22fVNkIbcdVhEYZy+u0cq9DzF2EVTPlY86HQ+sq4oAMurODE4ybh7nXhuGyfLhdK53CAYOQNtG8VoueCVE+CwGKLVH/hjwWoIiahgDQqvwXVGLSyHNHw61a4kR9zoI6CAksQ4HpZ9Z3sorOFtlKTFW6vEHvDjzoOwR3vmzVR7fZlsNI6iqig+LMBWCZaqT31sSX8MH74tX7dX1hmIerri8Jh+LKzBqcEbbsqLvjlX+g9FAf8NnOCk+BfyCxzYE5LWikMoufRHbUbvBNYmicQ9TFjHGHvRDDqkgQRhGa+l2nepWyPo0g9XVYSyI5GW0LOx/xy/zZyCJuuaJIawrvnVZsaqwP2P5Ut8GML3UkFLj7WWEj12A/rbxcK3MMhPxxCNKBjPoDra8xnOTYLYmZYdW2QknEDd+aBPmx0rGi5HmGQ5Nv6wquHEP4QyhXvH2CSJzbKLT11SzF98ME7RyToMe2245D3knaUE=
